language: java
install: true
sudo: false
jdk:
  - oraclejdk8
before_script: gradle clean
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/abfe24b913f95a8e20a2
    on_success: change
    on_failure: always
    on_start: never
  slack:
    secure: OpHPVXixQOZovw4OFZAeH9UsX8pqxt7RrrfzvlRq0khkV9KNWlOGPXVRLO1PpNlx3lGaLbPntz/XNqJImHRloZRPB40pZgqsoptO7yNGE4QfRwA5oQGt3nrGWbBG5CWLH/C5YvF/kRTV/4Mp/FoMjLFLlFOf0I3TG+EAUN1quTQ=
before_deploy: gradle installZip upgradeZip
deploy:
  provider: releases
  api_key:
    secure: arKEreSKqK8bbx13l5cduV9dn3ZQGdKs32B08V2rUUJWsJmoLc02VzJsQlSmdmUWBODNx/Vt6oi4pb0taea800caTY/4Vds2n4yAEov4a4sp4r4gOM3xkwzIIKISjzt0ShS4I8w5WlDt2qm2rahdOOCatgcVqGlpO/wuTmni/6k=
  file:
    - madcow-project/build/distributions/madcow-2.0-SNAPSHOT-install.zip
    - madcow-project/build/distributions/madcow-2.0-SNAPSHOT-upgrade.zip
  skip_cleanup: true
  on:
    tags: true
after_deploy: "echo deployment done"
after_success:
  - gradle coveralls
addons:
  sonarcloud:
    organization: "4impactSonar"
    token:
      secure: "i85TqgE6pEt/c8tArrYFom6HKcT5Z8VVmHYfTe5w3X0ifcx5x6Sb/O6rChcl+Q6KF+4m/vgAOyPAnfQiaiaFdpN21mWk5qtEPM/ih2AnL0KbpEcM1AIQbKD7k0y4Bm+JEkTKHgdmDxZ/BwhizMIVDEioDgreq/pUcO5UwFrlnBk="
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
